server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/gert/Development/Projects/spring-microservices-in-action/configurationserver/src/main/resources/config/licensingservice